services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  postgres_data:
