services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - next_network
  next:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: postgres
    networks:
      - next_network

networks:
  next_network:
    driver: bridge

volumes:
  postgres_data:
