services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
